// The web/native font split (FAB-19 F4), as a pure function so it is testable
// and so the rule lives in one place instead of inside a Vite plugin closure.
//
// THE PROBLEM. index.html carries a Google Fonts stylesheet plus its two
// preconnect hints. The Capacitor apps ship that same index.html, so every cold
// launch of the iOS and Android app hit fonts.googleapis.com and
// fonts.gstatic.com before the learner touched anything — disclosing the device
// IP and user-agent to Google, and leaving the app with no Chinese typeface at
// all when the device was offline.
//
// THE SPLIT.
//   * Web keeps the CDN. It is a browser, the CDN is cached across sites, and
//     18 MB of woff2 on a page load would be a real regression.
//   * Native bundles the same fonts locally (src/webfonts.css, generated by
//     fetch-webfonts.mjs) and these tags are removed from the HTML.
//
// Typography is unchanged either way: the bundled @font-face rules are the same
// families, weights and unicode-ranges Google serves.
//
// This is a BUILD-time split, not a runtime one, so it does not go through
// isNativeApp() — there is nothing to branch on at runtime, the tags are either
// in the shipped HTML or they are not. `grep -rn __DOJO_NATIVE_BUILD__` is the
// complete audit of the flag.

// Matches the Google Fonts stylesheet link, the two preconnect hints, and any
// HTML comment that documents them, so the native HTML has no dangling prose
// about fonts it no longer fetches.
const GOOGLE_FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com']

// A <link> tag (self-closing or not) pointing at either Google font host.
const GOOGLE_FONT_LINK = /[ \t]*<link\b[^>]*(?:fonts\.googleapis\.com|fonts\.gstatic\.com)[^>]*>\s*\n?/gi

// Is this HTML still asking a browser to contact Google for fonts?
export function hasGoogleFontRequest(html) {
  const text = String(html || '')
  // Only count real tags — a mention inside a comment is prose, not a request.
  const withoutComments = text.replace(/<!--[\s\S]*?-->/g, '')
  return GOOGLE_FONT_HOSTS.some(host => withoutComments.includes(host))
}

// Remove every Google Fonts <link> from the HTML. Returns { html, removed }.
// Nothing else in the document is touched — the bundled Mona Sans preload, the
// icons, the manifest and the meta tags all survive, because a font change has
// no business editing them.
export function stripGoogleFontTags(html) {
  const text = String(html || '')
  const matches = text.match(GOOGLE_FONT_LINK) || []
  return { html: text.replace(GOOGLE_FONT_LINK, ''), removed: matches.length }
}

// The families index.html asks Google for. fetch-webfonts.mjs must download
// exactly these, or the native build would silently lose a typeface — which is
// the one failure mode of this split that nothing else would catch.
export function googleFontFamilies(html) {
  const text = String(html || '')
  const link = (text.match(/<link\b[^>]*fonts\.googleapis\.com\/css2[^>]*>/i) || [])[0]
  if (!link) return []
  const href = (link.match(/href=["']([^"']+)["']/i) || [])[1] || ''
  // Split the QUERY off first. The first family sits directly after `?`, so
  // splitting the whole href on `&` leaves it glued to the origin and it gets
  // silently dropped — which would let a family go unbundled without the spec
  // below noticing.
  const query = href.slice(href.indexOf('?') + 1)
  return query
    .split('&')
    .filter(part => part.startsWith('family='))
    .map(part => decodeURIComponent(part.slice('family='.length).split(':')[0]).replace(/\+/g, ' '))
}
