import { anonTest, authedTest, expect } from '../fixtures/mockSupabase.js';

// Visual regression for the screens where a layout break wouldn't fail a
// role/text assertion — overlapping panels, clipped rows, a hero that lost its
// background. Each shot compares against a committed baseline in
// visual.spec.js-snapshots/.
//
// ⚠️ BASELINES ARE GENERATED BY CI, NEVER LOCALLY. Actions → "Visual
// regression baselines" runs this file with --update-snapshots on the same
// runner image the E2E workflow uses and commits the result back to the
// branch. A baseline captured on a laptop or sandbox rasterizes fonts
// differently and will fail in CI — if you see local failures here, that is
// why; the CI run is the verdict. To bless an intentional visual change,
// dispatch that workflow on your branch instead of updating locally.
//
// Determinism notes:
// - Fonts come from Google Fonts at runtime; every shot waits for
//   document.fonts.ready before capturing.
// - The Stories shelf's featured "today's story" is picked per-day among the
//   readable set, so the shelf shots serve exactly ONE readable story — a
//   pick among one is the same story every day.
// - Screens that render the real date (Home's 7-day forecast, the study
//   calendar) are deliberately not captured.

const DESKTOP = { width: 1280, height: 800 };
const MOBILE = { width: 390, height: 844 };

async function fontsReady(page) {
  await page.evaluate(() => document.fonts.ready);
}

anonTest.describe('visual: landing (logged out)', () => {
  anonTest('desktop', async ({ page }) => {
    await page.setViewportSize(DESKTOP);
    await page.goto('/');
    await expect(page.getByRole('button', { name: /Start your first story/i })).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('landing-desktop.png');
  });

  anonTest('mobile', async ({ page }) => {
    await page.setViewportSize(MOBILE);
    await page.goto('/');
    await expect(page.getByRole('button', { name: /Start your first story/i })).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('landing-mobile.png');
  });
});

anonTest.describe('visual: trust pages', () => {
  anonTest('privacy, desktop', async ({ page }) => {
    await page.setViewportSize(DESKTOP);
    await page.goto('/privacy');
    await expect(page.getByRole('heading', { name: /privacy/i }).first()).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('privacy-desktop.png');
  });
});

authedTest.describe('visual: stories shelf', () => {
  // One readable story at the learner's current level (mock track is level 2)
  // forces the featured pick; everything else on the shelf derives from it and
  // the fixture deck, so the composition never varies by date.
  const SOLO_STORY = {
    id: 'st-visual-1', language: 'chinese', system: 'hsk', level: 2, tier: 1,
    story_number: 1, title: '下雨了', is_published: true, presentation: 'paced',
    has_audio: false, image_path: null, english_content: 'It is raining.',
    content: ['今天下雨。', '我们回家。'].join('\n'),
  };

  authedTest.beforeEach(async ({ page }) => {
    await page.route('**/rest/v1/stories**', async (route) => {
      if (route.request().method() !== 'GET') return route.fallback();
      return route.fulfill({
        status: 200,
        headers: { 'access-control-allow-origin': '*', 'content-type': 'application/json' },
        body: JSON.stringify([SOLO_STORY]),
      });
    });
  });

  authedTest('desktop', async ({ page }) => {
    await page.setViewportSize(DESKTOP);
    await page.goto('/stories');
    await expect(page.getByRole('button', { name: /Featured for you/ })).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('stories-shelf-desktop.png');
  });

  authedTest('mobile', async ({ page }) => {
    await page.setViewportSize(MOBILE);
    await page.goto('/stories');
    await expect(page.getByRole('button', { name: /Featured for you/ })).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('stories-shelf-mobile.png');
  });
});
