import fs from 'node:fs';
import { anonTest, authedTest, expect } from '../fixtures/mockSupabase.js';

// Visual regression for the screens where a layout break wouldn't fail a
// role/text assertion — overlapping panels, clipped rows, a hero that lost its
// background. Each shot compares against a committed baseline in
// visual.spec.js-snapshots/.
//
// ⚠️ BASELINES ARE GENERATED BY CI, NEVER LOCALLY. Actions → "Visual
// regression baselines" runs this file with --update-snapshots on the same
// runner image the E2E workflow uses and commits the result back to the
// branch. A baseline captured on a laptop or sandbox rasterizes fonts
// differently and will fail in CI — if you see local failures here, that is
// why; the CI run is the verdict. To bless an intentional visual change,
// dispatch that workflow on your branch instead of updating locally.
//
// Determinism notes:
// - Fonts come from Google Fonts at runtime; every shot waits for
//   document.fonts.ready before capturing.
// - The Stories shelf's featured "today's story" is picked per-day among the
//   readable set, so the shelf shots serve exactly ONE readable story — a
//   pick among one is the same story every day.
// - Screens that render the real date (Home's 7-day forecast, the study
//   calendar) are deliberately not captured.

const DESKTOP = { width: 1280, height: 800 };
const MOBILE = { width: 390, height: 844 };

// Until the first baseline run has been committed, comparisons SKIP rather
// than fail — otherwise a fresh branch (or the repo before the baseline
// workflow ever ran) could never get a green E2E run. A --update-snapshots
// run (what visual-baseline.yml does) never skips, so the bootstrap is:
// merge, dispatch the workflow once, baselines exist, skips disappear.
const HAS_BASELINES = fs.existsSync(new URL('./visual.spec.js-snapshots', import.meta.url));

function skipWithoutBaselines(testObj, testInfo) {
  // A bare --update-snapshots maps to 'changed' on Playwright ≥1.49 ('all'
  // when passed explicitly) — both mean "we are capturing, don't skip".
  const updating = ['all', 'changed'].includes(testInfo.config.updateSnapshots);
  testObj.skip(
    !HAS_BASELINES && !updating,
    'No committed baselines yet — dispatch Actions → "Visual regression baselines" to create them'
  );
}

async function fontsReady(page) {
  await page.evaluate(() => document.fonts.ready);
}

anonTest.describe('visual: landing (logged out)', () => {
  anonTest('desktop', async ({ page }, testInfo) => {
    skipWithoutBaselines(anonTest, testInfo);
    await page.setViewportSize(DESKTOP);
    await page.goto('/');
    await expect(page.getByRole('button', { name: /Start your first story/i })).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('landing-desktop.png');
  });

  anonTest('mobile', async ({ page }, testInfo) => {
    skipWithoutBaselines(anonTest, testInfo);
    await page.setViewportSize(MOBILE);
    await page.goto('/');
    await expect(page.getByRole('button', { name: /Start your first story/i })).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('landing-mobile.png');
  });
});

anonTest.describe('visual: trust pages', () => {
  anonTest('privacy, desktop', async ({ page }, testInfo) => {
    skipWithoutBaselines(anonTest, testInfo);
    await page.setViewportSize(DESKTOP);
    await page.goto('/privacy');
    await expect(page.getByRole('heading', { name: /privacy/i }).first()).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('privacy-desktop.png');
  });
});

authedTest.describe('visual: stories shelf', () => {
  // One readable story at the learner's current level (mock track is level 2)
  // forces the featured pick; everything else on the shelf derives from it and
  // the fixture deck, so the composition never varies by date.
  const SOLO_STORY = {
    id: 'st-visual-1', language: 'chinese', system: 'hsk', level: 2, tier: 1,
    story_number: 1, title: '下雨了', is_published: true, presentation: 'paced',
    has_audio: false, image_path: null, english_content: 'It is raining.',
    content: ['今天下雨。', '我们回家。'].join('\n'),
  };

  authedTest.beforeEach(async ({ page }) => {
    await page.route('**/rest/v1/stories**', async (route) => {
      if (route.request().method() !== 'GET') return route.fallback();
      return route.fulfill({
        status: 200,
        headers: { 'access-control-allow-origin': '*', 'content-type': 'application/json' },
        body: JSON.stringify([SOLO_STORY]),
      });
    });
  });

  authedTest('desktop', async ({ page }, testInfo) => {
    skipWithoutBaselines(authedTest, testInfo);
    await page.setViewportSize(DESKTOP);
    await page.goto('/stories');
    await expect(page.locator('button[data-continue-card]')).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('stories-shelf-desktop.png');
  });

  authedTest('mobile', async ({ page }, testInfo) => {
    skipWithoutBaselines(authedTest, testInfo);
    await page.setViewportSize(MOBILE);
    await page.goto('/stories');
    await expect(page.locator('button[data-continue-card]')).toBeVisible();
    await fontsReady(page);
    await expect(page).toHaveScreenshot('stories-shelf-mobile.png');
  });
});
