// The app's typefaces, bundled.
//
// They used to come from a render-blocking <link> to fonts.googleapis.com in
// index.html. In a browser that is a defensible trade; inside a store app it is
// a bug with three faces:
//
//   - The first paint of a *downloaded native app* waited on a third-party
//     network round-trip. Open the app on a train and the launch stalls on
//     someone else's CDN.
//   - Offline, the app rendered in the platform's default sans — and the
//     hanzi, which are the product, fell back to whatever CJK face the device
//     happened to have.
//   - It leaked a request to Google on every launch, which is a privacy answer
//     we would rather not have to give in a store questionnaire.
//
// So the faces ship inside the bundle. Vite fingerprints and copies them into
// dist/client, and `cap sync` copies that into both app bundles: no network, no
// FOUT, identical rendering on a plane.
//
// ── What is imported, and why exactly this ───────────────────────────────
//
// **Inter, static, weights 300/400/500/600.** Exactly the four the Google
// stylesheet was requesting, so rendering is unchanged — including the places
// the app asks for 650/700/750/800 and the browser synthesises them, which it
// was already doing. Swapping in the variable face would render those properly
// and is a genuine improvement, but it is a *visual* change and this phase is
// the native foundation only.
//
// **Latin + Cyrillic subsets.** Latin covers the product. Cyrillic is 60 KB of
// insurance so the frozen Russian track keeps rendering as it does today rather
// than degrading to a system face.
//
// **Poppins 500/600/700, Latin.** The wordmark (brand.js) and nothing else.
//
// **Noto Sans SC, VARIABLE.** The one real decision here. The static family is
// ~3.7 MB per weight, and the app uses four (300/400/500/700) — ~15 MB. The
// variable face carries the whole 100–900 axis in 4.6 MB total, across the same
// 101 unicode-range subsets, so every weight the app asks for renders as a real
// weight and the bundle is a third of the size. The browser only ever decodes
// the subsets a screen actually contains.
//
// Noto Sans JP is deliberately NOT here: it is loaded on demand by
// fontLoader.js for the paused Japanese track, so nobody downloads a second CJK
// family for a language they will never open.

// Inter — the UI face.
import '@fontsource/inter/latin-300.css'
import '@fontsource/inter/latin-400.css'
import '@fontsource/inter/latin-500.css'
import '@fontsource/inter/latin-600.css'
import '@fontsource/inter/latin-ext-300.css'
import '@fontsource/inter/latin-ext-400.css'
import '@fontsource/inter/latin-ext-500.css'
import '@fontsource/inter/latin-ext-600.css'
import '@fontsource/inter/cyrillic-400.css'
import '@fontsource/inter/cyrillic-500.css'
import '@fontsource/inter/cyrillic-600.css'

// Poppins — the wordmark only.
import '@fontsource/poppins/latin-500.css'
import '@fontsource/poppins/latin-600.css'
import '@fontsource/poppins/latin-700.css'

// Noto Sans SC — the product. One variable face, every weight.
//
// Not the package's own stylesheet: it declares the family as 'Noto Sans SC
// Variable', and the app says 'Noto Sans SC' in ~30 places including
// DojoHQ.css. notoSansSC.css is the same 101 subsets under the name already in
// use, generated by scripts/build-noto-sans-sc-css.mjs.
import './notoSansSC.css'
