-- Per-line story narration (product review item #12): real TTS audio for
-- stories, generated by generate-story-audio.mjs into the existing public
-- `audio` bucket at stories/{story_id}/{line_index}.mp3. `has_audio` is only
-- set true once every line for a story synthesized successfully, so the
-- reader can go straight to bucket audio without probing per line — stories
-- still awaiting generation keep using the browser's speechSynthesis fallback
-- with zero added latency.

alter table public.stories add column if not exists has_audio boolean not null default false;

notify pgrst, 'reload schema';
